spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password

  liquibase:
    enabled: true
    drop-first: false
    default-schema: public

logging:
  level:
    liquibase: info